import GlassPane from '@/components/GlassPane';
import '@/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  signin: React.ReactNode;
  home: React.ReactNode;
}

export default function RootLayout({ signin, home }: RootLayoutProps) {
  const isLoggedIn = false;
  return (
    <html lang="en">
      <body className="h-screen w-screen rainbow-mesh p-6">
        <GlassPane className="w-full h-full flex items-center justify-center">
          {isLoggedIn ? home : signin}
        </GlassPane>
      </body>
    </html>
  );
}
