import GlassPane from '@/components/GlassPane';
import '@/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  auth: React.ReactNode;
  dashboard: React.ReactNode;
}

export default function RootLayout({ auth, dashboard }: RootLayoutProps) {
  const isLoggedIn = false;
  return (
    <html lang="en">
      <body className="h-screen w-screen rainbow-mesh p-6">
        <GlassPane className="w-full h-full flex items-center justify-center">
          {isLoggedIn ? dashboard : auth}
        </GlassPane>
      </body>
    </html>
  );
}
