import GlassPane from '@/components/GlassPane';
import { cookies } from 'next/headers';
import { validateJWT } from '@/utils/auth';

import '@/styles/globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

interface RootLayoutProps {
  auth: React.ReactNode;
  dashboard: React.ReactNode;
}

export default async function RootLayout({ auth, dashboard }: RootLayoutProps) {
  const cookieStore = cookies();
  const jwt = cookieStore.get('jwt');
  let isValid = false;

  try {
    const payload = await validateJWT(jwt!.value);
    //console.log(payload);
    isValid = true;
  } catch (err) {
    isValid = false;
  }
  console.log(isValid);
  return (
    <html lang="en">
      <body className="h-screen w-screen rainbow-mesh p-6">
        <GlassPane className="w-full h-full flex items-center justify-center">
          {isValid ? dashboard : auth}
        </GlassPane>
      </body>
    </html>
  );
}
